import {Platform, StyleSheet} from 'react-native';

const widthPreparatStyle1 = '100%';

export const gStyle = StyleSheet.create({
    container: {
        flex: 1,
        // backgroundColor: '#E4EBF5',
        backgroundColor: '#DEE9FD',
        flexDirection: 'column',
    },
    box1: {
        // flex: 1,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '35%': '60%',
    },
    box2: {
        // flex: 3,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '65%': '57%',
    },
    box11: {
        // flex: 1,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '86%': '91%',
    },
    box22: {
        // flex: 3,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '24%': '35%',
    },
    box111: {
        // flex: 1,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '86%': '91%',
    },
    box222: {
        // flex: 3,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '13%': '20%',
        // top: Platform.OS === "ios" ? '20%': '24%',

    },
    boxContainer1: {
        backgroundColor: '#E4EBF5',
        height: Platform.OS === "ios" ? '50%': '40%',
    },
    boxContainer2: {
        backgroundColor: '#E4EBF5',
        height: Platform.OS === "ios" ? '50%': '60%',
        top: Platform.OS === "ios" ? '20%': '42%',
    },
    paginatorNumberCircle: {
        flexDirection: 'row',
        // height: 0.5,
        // marginTop: -650,
        marginLeft: '38%',
        top: Platform.OS === "ios" ? '-60%': '-60%',
        left: '5%',
        // blurRadius: 2,
    },
    paginatorNumberCircleContact: {
        flexDirection: 'row',
        // height: 0.5,
        // marginTop: -650,
        marginLeft: '38%',
        top: Platform.OS === "ios" ? '-50%': '-83%',
        left: Platform.OS === "ios" ? '-40%': '-20%',
        // blurRadius: 2,
    },
    paginatorNumberCircleContact1: {
        flexDirection: 'row',
        // height: 0.5,
        // marginTop: -650,
        marginLeft: '38%',
        top: Platform.OS === "ios" ? '-50%': '-80%',
        left: Platform.OS === "ios" ? '-40%': '-20%',
        // blurRadius: 2,
    },
    paginatorNumberCircleContact2: {
        flexDirection: 'row',
        // height: 0.5,
        // marginTop: -650,
        marginLeft: '38%',
        top: Platform.OS === "ios" ? '-50%': '-74%',
        left: Platform.OS === "ios" ? '-40%': '-20%',
        // blurRadius: 2,
    },
    box1111: {
        // flex: 1,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '34%': '50%',
    },
    box2222: {
        // flex: 3,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '75%': '35%',
        top: Platform.OS === "ios" ? '25%': '27%',
    },
    box11111: {
        // flex: 1,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '86%': '90%',
        // padding: 10,
    },
    box22222: {
        // flex: 3,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '14%': '10%',
        // top: Platform.OS === "ios" ? '25%': '27%',
    },
    box111111: {
        // flex: 1,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '35%': '57%',
    },
    box222222: {
        // flex: 3,
        backgroundColor: '#E4EBF5',
        // flexDirection: 'column',
        height: Platform.OS === "ios" ? '65%': '57%',
    },
    image: {
        backgroundColor: '#E4EBF5',
        width:  Platform.OS === "ios" ? '100%': '100%',
        // width:  '100%',
        height: 140,
        borderRadius: 25,
        // не пашет тк в Pin.js const [ratio, setRatio] = useState(1);
        // и в стилях компонента { aspectRatio: ratio } применили
        // aspectRatio: Platform.OS === "ios" ? 1 / 1.4 :  1 / 1,
    },
    textGorStyle1: {
        fontSize: 20,
        fontWeight: 'bold',
        margin: 10,
    },
    pin: {
        width: '100%',
    },

    boxContainer: {
        // width: '50%',
        // height: '50%',
        backgroundColor: '#E4EBF5',
        padding: 2,
        flexDirection: 'column',
        // flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        // top: Platform.OS === "ios" ? '-40%' : '-60%',
    },
    boxContactImage: {

        width: '100%',
        // height: Platform.OS === "ios" ? '35%': '55%',
        backgroundColor: '#E4EBF5',
        padding: 5,
    },
    boxContactForm: {
        width: '100%',
        height: '100%',
        backgroundColor: '#E4EBF5',
        padding: 5,
        // marginTop: Platform.OS === "ios" ? '80%' : '80%',
    },
    inner: {
        flex: 1,
        width: '100%',
        height: '100%',
        backgroundColor: '#E4EBF5',
        // marginTop: '12%',
    },
    separator: {
        marginVertical: Platform.OS === "ios" ? 10 : 7,
        borderBottomColor: '#737373',
        borderBottomWidth: StyleSheet.hairlineWidth,
    },

    boxContainerMain: {
        width: '100%',
        height: '100%',
        backgroundColor: '#E4EBF5',
        padding: 2,
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'center',
        alignItems: 'center',
        // top: Platform.OS === "ios" ? '-40%' : '-50%',
    },
    // box: {
    //     width: '90%',
    //     height: '90%',
    //     backgroundColor: '#E4EBF5',
    //     padding: 5,
    // },
    main: {
        borderWidth: 1,
        borderColor: '#6E5573',
        borderRadius: 15,
        width: '60%',
        height: '80%',
        left: '37%',
        top: '10%'
    },
    main_menu: {
        borderWidth: 1,
        borderColor: '#6E5573',
        borderRadius: 25,
        width: '67%',
        height: '80%',
        left: '31%',
        top: '10%',
        // backgroundColor: '#E4EBF5',
        backgroundColor: '#DEE9FD',
    },
    boxMain: {
        width: '90%',
        height: '90%',
        backgroundColor: '#E4EBF5',
        padding: 5,
    },
    innerMain: {
        flex: 1,
        width: '100%',
        height: '100%',
        backgroundColor: '#E4EBF5',
        // marginTop: '12%',
    },
    boxContactPaginator: {
        width: '100%',
        top: Platform.OS === "ios" ? '20%': '20%',
        // height: Platform.OS === "ios" ? '35%': '55%',
        backgroundColor: '#E4EBF5',
        padding: 5,
    },
    innerPaginator: {
        flex: 1,
        justifyContent: 'flex-start',
        // width: '100%',
        // height: '10%',
        top: -50,
    },
    innerPersonal: {
        flex: 1,
    },
    innerPersonalText: {
        // flex: 0.1,
        // flexDirection: 'row',
        // flexWrap: 'wrap',
        // color: '#B78DBE',
        // width: Platform.OS === "ios" ? '110%' : '100%',
        // height: Platform.OS === "ios" ? '110%' : '100%',
        // marginLeft: 5,
        // top: -80,
        // justifyContent: 'flex-start',
        // flex: 0.1,
        // justifyContent: 'space-between',
        // width: '370',
        // padding: '18',
        // flexWrap: 'wrap',
    },
    screenMainHeader: {
        title: '',
        width: '100%',
        height: '15%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    header: {
        width: '100%',
        height: '55%',
        alignItems: 'center',
        justifyContent: 'center',
    },
    titleOnco: {
        fontSize: Platform.OS === "ios" ? 55 : 60,
        color: '#554357',
        fontFamily: Platform.OS === "ios" ? 'zapfino-extra-lt-pro' : 'zapfino-extra-lt-pro',
        top: Platform.OS === "ios" ? '5%' : '5%', // явное указание из-за разницы между шрифтами
    },
    title: {
        fontSize: Platform.OS === "ios" ? 14 : 18,
        color: '#554357',
        // fontFamily: Platform.OS === "ios" ? 'zapfino-extra-lt-pro' : 'zapfino-extra-lt-pro',
        top: Platform.OS === "ios" ? '30%' : '30%', // явное указание из-за разницы между шрифтами
        width: '90%',
        textAlign: 'left',
        padding: 15,
    },
    titleMainMenu: {
        fontSize: Platform.OS === "ios" ? 14 : 18,
        color: '#554357',
        // fontFamily: Platform.OS === "ios" ? 'zapfino-extra-lt-pro' : 'zapfino-extra-lt-pro',
        top: Platform.OS === "ios" ? '8%' : '30%', // явное указание из-за разницы между шрифтами
        width: '90%',
        textAlign: 'left',
        padding: 15,
    },
    fontTitle: {
        fontFamily: Platform.OS === "ios" ? 'zapfino-extra-lt-pro' : 'zapfino-extra-lt',
        fontSize: Platform.OS === "ios" ? 45 : 30,
        color: '#6E5573',
    },
    h2: {
        fontSize: Platform.OS === "ios" ? 15 : 20,
        color: '#A88EC1',
        top: Platform.OS === "ios" ? -3 : 13,
    },
    h3: {
        fontSize: Platform.OS === "ios" ? 12 : 15,
        color: '#A88EC1',
        top: Platform.OS === "ios" ? 2 : 38,
    },
    h4: {
        fontSize: Platform.OS === "ios" ? 12 : 15,
        color: '#A88EC1',
        top: Platform.OS === "ios" ? -55 : -18,
    },
    h5: {
        fontSize: Platform.OS === "ios" ? 11 : 15,
        color: '#A88EC1',
        // top: Platform.OS === "ios" ? -65 : -110,
    }
})

// screenContactsHeader: {
//     title: 'OncoAssist',
//     fontWeight: "400",
//     fontFamily: 'zapfino-extra-lt-pro',
//     fontSize: Platform.OS === "ios" ? 38 : 48,
// },
